name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: |
          cd az_appgw
          terraform init -backend-config=backend.config

      - name: Terraform Validate
        run: |
          cd az_appgw
          terraform validate

      - name: Terraform Plan
        run: |
          cd az_appgw
          terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: |
          cd az_appgw
          terraform apply -var-file="terraform.tfvars" -auto-approve
